[device]
DEVICE_NAME = "shiba"
ROM_FAMILY = "grapheneos"
'GRAPHENEOS[UPDATE_CHANNEL]' = "stable"

[build]
ROOT = false
ROOT_MODE = "both"
MAGISK_PREINIT = "sda10"
'ADDITIONALS[AFSR]' = true
'ADDITIONALS[ALTERINSTALLER]' = true
'ADDITIONALS[BCR]' = true
'ADDITIONALS[CUSTOTA]' = true
'ADDITIONALS[MSD]' = true
'ADDITIONALS[OEMUNLOCKONBOOT]' = true
'ADDITIONALS[FDROID_PRIVILEGED_EXTENSION]' = false
'ADDITIONALS[BOOT_ANIMATION]' = true
'ADDITIONALS[MAS_COMPATIBLE_SEPOLICY]' = false
FORCE_UPDATE = false
