[device]
DEVICE_NAME = "pdx235"
ROM_FAMILY = "lineageos"
'GRAPHENEOS[UPDATE_CHANNEL]' = "nightly"

[build]
ROOT = false
MAGISK_PREINIT = "sda47"
'ADDITIONALS[AFSR]' = true
'ADDITIONALS[ALTERINSTALLER]' = true
'ADDITIONALS[BCR]' = true
'ADDITIONALS[CUSTOTA]' = true
'ADDITIONALS[MSD]' = true
'ADDITIONALS[OEMUNLOCKONBOOT]' = true
'ADDITIONALS[FDROID_PRIVILEGED_EXTENSION]' = false
'ADDITIONALS[BOOT_ANIMATION]' = true
'ADDITIONALS[MAS_COMPATIBLE_SEPOLICY]' = true
FORCE_UPDATE = false
