name: Patch and Release LineageOS OTA

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      device-id:
        description: Device code name
        required: true
        default: "pdx235"
      root:
        description: Add root to the build
        required: false
        type: boolean
        default: true
      magisk-preinit-device:
        description: Magisk preinit device
        required: false
        default: "sda47"
      update-channel:
        description: LineageOS update channel
        required: false
        default: "nightly"
      compatible-sepolicy-patching:
        description: Enable compatible SELinux patching
        required: false
        type: boolean
        default: true
      allow-unauthorized-adb:
        description: Enable unauthorized ADB for build-only debugging
        required: false
        type: boolean
        default: false
      release-type:
        description: Release behavior
        required: true
        type: choice
        options:
          - default
          - build-only
          - force-publish
        default: default

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-rom.yml
    with:
      rom-family: lineageos
      device-id: ${{ inputs.device-id || 'pdx235' }}
      root: ${{ github.event_name == 'workflow_dispatch' && inputs.root || false }}
      magisk-preinit-device: ${{ inputs.magisk-preinit-device || 'sda47' }}
      update-channel: ${{ inputs.update-channel || 'nightly' }}
      compatible-sepolicy-patching: ${{ github.event_name == 'schedule' || inputs.compatible-sepolicy-patching }}
      allow-unauthorized-adb: ${{ github.event_name == 'workflow_dispatch' && inputs.allow-unauthorized-adb || false }}
      release-type: ${{ github.event_name == 'schedule' && 'default' || inputs.release-type }}
      publish: ${{ github.event_name == 'schedule' || inputs.release-type != 'build-only' }}
    secrets: inherit
