name: Patch and Release OTA

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (UTC)
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      device-id:
        description: Device ID
        required: true
      ota-version:
        description: OTA version. By default, runs against latest version
        required: false
      force-ota-server-upload:
        description: Force OTA server upload
        required: false
        type: boolean
      root:
        description: Add root to the build
        required: false
        type: boolean
      magisk-preinit-device:
        description: Magisk preinit device. For example, "sda8"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVICE_NAME: "bluejay"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Allow for switching to github-pages branch
          fetch-depth: 0

      - name: Patch OTA
        shell: bash
        env:
          ADDITIONALS[ROOT]: ${{ github.event.inputs.root }}
          CLEANUP: true
          GRAPHENEOS[VERSION]: ${{ github.event.inputs.ota-version }}
          FORCE_UPDATE: ${{ github.event.inputs.force-ota-server-upload }}
          MAGISK[PREINTI]: ${{ github.event.inputs.magisk-preinit-device }}
        run: |
          echo "DEVICE_NAME=${{ github.event.inputs.device-id || env.DEVICE_NAME }}" >> $GITHUB_ENV
          echo "Running release script"
          src/main.sh
