name: Patch and Release OTA

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (UTC)
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      device-id:
        description: Device ID
        required: true
      ota-version:
        description: OTA version. By default, runs against latest version
        required: false
      force-update:
        description: Forcefully upload OTA to the server
        required: false
        type: boolean
      root:
        description: Add root to the build
        required: false
        type: boolean
        default: false
      magisk-preinit-device:
        description: Magisk preinit device. For example, "sda8"
        required: false
      update-channel:
        description: GrapheneOS update channel. Supports `alpha`, `beta` and `stable`. Defaults to `alpha`
        required: false
        default: "alpha"

env:
  CARGO_INCREMENTAL: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      DEVICE_NAME: "bluejay"
      INTERACTIVE_MODE: "false"

    steps:
      - name: Check if `root` is true and `magisk-preinit-device` is set
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          # Convert inputs to proper boolean values
          root=${{ github.event.inputs.root }}
          magisk_preinit_device=${{ github.event.inputs.magisk-preinit-device }}
          
          # Ensure that the boolean comparison is correctly handled
          if [ "$root" == "true" ] && [ -z "$magisk_preinit_device" ]; then
            echo "::error:: magisk-preinit-device is required when root is true."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Allow for switching to github-pages branch
          fetch-depth: 0

      - name: Check if a build exist already
        shell: bash
        run: |
          echo "HI, TBU"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable 2 weeks ago
                
      - name: Build and Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2.7.0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12-dev'

      - name: Setup Environment variables
        run: |
          echo "KEYS_AVB_BASE64=${{ secrets.AVB_KEY }}" >> $GITHUB_ENV
          echo "KEYS_CERT_OTA_BASE64=${{ secrets.CERT_OTA }}" >> $GITHUB_ENV
          echo "KEYS_OTA_BASE64=${{ secrets.OTA_KEY }}" >> $GITHUB_ENV

      - name: Patch OTA
        shell: bash
        env:
          ADDITIONALS_ROOT: ${{ github.event.inputs.root }}
          CLEANUP: true
          FORCE_UPDATE: ${{ github.event.inputs.force-update }}
          GRAPHENEOS_VERSION: ${{ github.event.inputs.ota-version }}
          MAGISK_PREINIT: ${{ github.event.inputs.magisk-preinit-device }}
          PASSPHRASE_AVB: ${{ secrets.PASSPHRASE_AVB }}
          PASSPHRASE_OTA: ${{ secrets.PASSPHRASE_OTA }}
        run: |
          echo "DEVICE_NAME=${{ github.event.inputs.device-id || env.DEVICE_NAME }}" >> $GITHUB_ENV
          echo "Running release script"
          src/main.sh

      - name: Access envs
        run: |
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi
          echo "GRAPHENEOS_OTA_TARGET=${GRAPHENEOS_OTA_TARGET}" >> $GITHUB_ENV
          echo "GRAPHENEOS_VERSION=${GRAPHENEOS_VERSION}" >> $GITHUB_ENV
          echo "OUTPUT_PATCHED_OTA=${OUTPUT_PATCHED_OTA}" >> $GITHUB_ENV
          echo "WORKDIR=${WORKDIR}" >> $GITHUB_ENV

      - name: Generate Changelog
        run: echo -e "See [Changelog](https://grapheneos.org/releases#${{ env.GRAPHENEOS_VERSION }})." > ${{ github.workspace }}-CHANGELOG.txt
        
      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            ${{ env.OUTPUT_PATCHED_OTA }}
            ${{ env.OUTPUT_PATCHED_OTA }}.csig
          name: "${{ env.GRAPHENEOS_VERSION }}"
          tag_name: "${{ env.GRAPHENEOS_VERSION }}"
            
      - name: Publish OTA to server
        shell: bash
        run: |
          CURRENT_COMMIT=$(git rev-parse --short HEAD)
          FLAVOR=("magisk" "rootless")
          root=${{ github.event.inputs.root }}
          
          mkdir -p "${FLAVOR}"
          
          git checkout gh-pages
          echo "Updating Configs for the new release..."
          
          if [ "${root}" = "true" ] || grep -q magisk "${DEVICE_NAME}.json"; then
            TARGET_FILE="${FLAVOR[0]}/${DEVICE_NAME}.json"
          else
            TARGET_FILE="${FLAVOR[1]}/${DEVICE_NAME}.json"
          fi
          
          echo "Updating Configs for the new release..."

          # Check if the target file exists, if not create an empty one
          if [ ! -f "${TARGET_FILE}" ]; then
            echo "touching ${TARGET_FILE}..."
            touch "${TARGET_FILE}"
          fi

          if ! grep -q "${{ env.GRAPHENEOS_VERSION }}" "${TARGET_FILE}" || [[ "${{ github.event.inputs.force-update || false }}" == 'true' ]]; then
            echo "Copying ${{ env.DEVICE_NAME }}.json to ${TARGET_FILE}..."
            cp "${{ env.DEVICE_NAME }}.json" "${TARGET_FILE}"
            git add "${TARGET_FILE}"
          else
            echo -e "Deployed version (${{ env.GRAPHENEOS_VERSION }}) is same as current GrapheneOS release (${{ env.REMOTE_GRAPHENEOS_VERSION }}) and \`FORCE_UPDATE\` is \`false\`.\nUpdate skipped."
          fi

          if ! git diff-index --quiet HEAD; then
            git commit -m "release("${CURRENT_COMMIT}"): bump GrapheneOS version to ${{ env.GRAPHENEOS_VERSION }}"
            git push origin gh-pages
          fi
          git checkout main
